#!/usr/bin/env bash
# Host-side deploy for the self-hosted gnomon dashboard.
#
#   ./deploy.sh <image-tag>
#
# Copied to ~/gnomon by .github/workflows/dashboard-deploy.yml, but designed to
# be run by hand — that is the rollback path. With tmp/image.tar.gz present the
# tag is loaded from it; without, the tag must already be in the local store.
#
# Env: HTTP_PORT (80), HEALTH_TIMEOUT (60), HEALTH_INTERVAL (2)
set -euo pipefail

cd "$(dirname "$0")"

# shellcheck disable=SC2034 # consumed by load_image/prune_images, added in Task 3/4
IMAGE_REPO=gnomon-dashboard
# shellcheck disable=SC2034 # consumed by load_image, added in Task 3
TARBALL=tmp/image.tar.gz
HTTP_PORT="${HTTP_PORT:-80}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-60}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-2}"

die() {
  echo "deploy: $*" >&2
  exit 1
}

preflight() {
  docker version >/dev/null 2>&1 || die \
    "cannot reach the Docker daemon as $(id -un). Install Docker Engine and add this user to the docker group: sudo usermod -aG docker $(id -un) — then log out and back in."
  docker compose version >/dev/null 2>&1 || die \
    "the Docker Compose plugin is missing. Install docker-compose-plugin (v2); the standalone docker-compose script is not used here."
  mkdir -p data tmp
  # Checked before anything starts: a data/ the container cannot write to
  # otherwise surfaces as a confusing SQLite SQLITE_CANTOPEN *after* an
  # apparently green deploy.
  [ -w data ] || die \
    "$(pwd)/data is not writable by $(id -un). The container writes the SQLite DB there. Fix with: sudo chown -R $(id -u):$(id -g) $(pwd)/data"
}

# The tag currently deployed, or empty on a first deploy.
current_tag() {
  [ -f .env ] || return 0
  sed -n 's/^IMAGE_TAG=//p' .env | tail -n1
}

# $1 = IMAGE_TAG, $2 = PREVIOUS_TAG
write_env() {
  cat > .env <<EOF
# GENERATED BY deploy.sh — do not hand-edit; the next deploy overwrites it.
# Compose interpolation only. Application secrets live in app.env.
IMAGE_TAG=$1
PREVIOUS_TAG=$2
DEPLOY_UID=$(id -u)
DEPLOY_GID=$(id -g)
HTTP_PORT=$HTTP_PORT
EOF
}

TAG="${1:-}"
[ -n "$TAG" ] || {
  echo "usage: deploy.sh <image-tag>" >&2
  exit 2
}

preflight

PREVIOUS_TAG="$(current_tag)"
write_env "$TAG" "$PREVIOUS_TAG"
