#!/usr/bin/env bash
# Host-side deploy for the self-hosted gnomon dashboard.
#
#   ./deploy.sh <image-tag>
#
# Copied to ~/gnomon by .github/workflows/dashboard-deploy.yml, but designed to
# be run by hand — that is the rollback path. With tmp/image.tar.gz present the
# tag is loaded from it; without, the tag must already be in the local store.
#
# Env: HTTP_PORT (the last deployed value, else 80), HEALTH_TIMEOUT (60),
#      HEALTH_INTERVAL (2)
set -euo pipefail

# Defined first: the guards below the cd already need it.
die() {
  echo "deploy: $*" >&2
  exit 1
}

cd "$(dirname "$0")" || die "cannot enter the script's own directory"
# `cd ""` succeeds silently in bash, so a failed dirname would leave us in the
# caller's cwd and run compose against whatever project lives there.
[ -f docker-compose.yml ] || die "docker-compose.yml is not in $(pwd) — run this from the deployment directory (~/gnomon on the VM)"

IMAGE_REPO=gnomon-dashboard
TARBALL=tmp/image.tar.gz
# A manual rollback that omits HTTP_PORT must not silently move the published
# port: the health gate would still pass, because it polls whatever port it
# just chose. Read after the cd, since .env is relative to the deployment
# directory; the -f guard keeps sed off the path entirely on a first deploy.
if [ -z "${HTTP_PORT:-}" ] && [ -f .env ]; then
  HTTP_PORT="$(sed -n 's/^HTTP_PORT=//p' .env | tail -n1)"
fi
HTTP_PORT="${HTTP_PORT:-80}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-60}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-2}"

preflight() {
  docker version >/dev/null 2>&1 || die \
    "cannot reach the Docker daemon as $(id -un). Install Docker Engine and add this user to the docker group: sudo usermod -aG docker $(id -un) — then log out and back in."
  docker compose version >/dev/null 2>&1 || die \
    "the Docker Compose plugin is missing. Install docker-compose-plugin (v2); the standalone docker-compose script is not used here."
  # healthy() polls the published port with curl. Without it every poll fails
  # with 127 and a perfectly healthy container gets rolled back, reported as a
  # health-check failure — the most misleading outcome this script can produce.
  command -v curl >/dev/null 2>&1 || die \
    "curl is not installed, and the health gate needs it. Install it: sudo apt-get install -y curl"
  mkdir -p data tmp || die "cannot create data/ and tmp/ in $(pwd)"
  # Checked before anything starts: a data/ the container cannot write to
  # otherwise surfaces as a confusing SQLite SQLITE_CANTOPEN *after* an
  # apparently green deploy.
  [ -w data ] || die \
    "$(pwd)/data is not writable by $(id -un). The container writes the SQLite DB there. Fix with: sudo chown -R $(id -u):$(id -g) $(pwd)/data"
}

# The tag currently deployed, or empty on a first deploy.
current_tag() {
  [ -f .env ] || return 0
  sed -n 's/^IMAGE_TAG=//p' .env | tail -n1
}

# $1 = IMAGE_TAG, $2 = PREVIOUS_TAG
write_env() {
  cat > .env <<EOF
# GENERATED BY deploy.sh — do not hand-edit; the next deploy overwrites it.
# Compose interpolation only. Application secrets live in app.env.
IMAGE_TAG=$1
PREVIOUS_TAG=$2
DEPLOY_UID=$(id -u)
DEPLOY_GID=$(id -g)
HTTP_PORT=$HTTP_PORT
EOF
}

load_image() {
  if [ -f "$TARBALL" ]; then
    gunzip -c "$TARBALL" | docker load || die "failed to load $TARBALL — the tarball may be truncated or corrupt, or the disk may be full. Check free space with df -h, then re-run the deploy to ship a fresh copy."
    rm -f "$TARBALL"
  fi
  docker image inspect "$IMAGE_REPO:$TAG" >/dev/null 2>&1 || die \
    "image $IMAGE_REPO:$TAG is not in the local store and no $TARBALL was supplied. To roll back, pass a tag that is still loaded: docker image ls $IMAGE_REPO"
}

# Polls the published port from the host — the same endpoint
# .github/workflows/dashboard-image.yml already uses as a readiness probe.
healthy() {
  local deadline=$((SECONDS + HEALTH_TIMEOUT))
  while [ "$SECONDS" -lt "$deadline" ]; do
    if curl -fsS -o /dev/null "http://127.0.0.1:$HTTP_PORT/"; then
      return 0
    fi
    sleep "$HEALTH_INTERVAL"
  done
  return 1
}

# Removes gnomon-dashboard images other than the two kept tags. Scoped to this
# repository name only — it must never touch anything else running on the box.
prune_images() {
  local keep_a="$1" keep_b="$2" tag
  while read -r tag; do
    case "$tag" in
      "" | "<none>" | "$keep_a" | "$keep_b") continue ;;
    esac
    docker image rm "$IMAGE_REPO:$tag" >/dev/null 2>&1 || true
  done < <(docker image ls "$IMAGE_REPO" --format '{{.Tag}}')
}

# Both post-start failures leave the box in the same state — .env already
# advanced to a tag that is not serving — so they take the same recovery path.
rollback_or_die() {
  echo "deploy: $1" >&2
  docker compose logs --tail=100 >&2 || true

  if [ -z "$PREVIOUS_TAG" ]; then
    die "no previous image to roll back to (first deploy). The box is NOT serving — fix the image and deploy again."
  fi
  if [ "$PREVIOUS_TAG" = "$TAG" ]; then
    die "the previous tag is the same failing image ($TAG), so there is nothing to roll back to. The box is NOT serving."
  fi

  echo "deploy: rolling back to $IMAGE_REPO:$PREVIOUS_TAG" >&2
  # PREVIOUS_TAG stays pointing at itself, so the next deploy's rollback target
  # is this known-good image rather than the one that just failed.
  write_env "$PREVIOUS_TAG" "$PREVIOUS_TAG"
  docker compose up -d --remove-orphans \
    || die "the rollback to $PREVIOUS_TAG could not even start. The box is NOT serving — investigate now."

  if healthy; then
    die "rolled back to $PREVIOUS_TAG, which is serving. $TAG was NOT deployed."
  fi
  die "the rollback to $PREVIOUS_TAG ALSO failed its health check. The box is NOT serving — investigate now."
}

TAG="${1:-}"
[ -n "$TAG" ] || {
  echo "usage: deploy.sh <image-tag>" >&2
  exit 2
}

preflight

# Unconditional: a failure anywhere below must not leave hundreds of megabytes
# sitting in the operator's home directory.
trap 'rm -f "$TARBALL"' EXIT

load_image

PREVIOUS_TAG="$(current_tag)"
write_env "$TAG" "$PREVIOUS_TAG"

echo "deploy: starting $IMAGE_REPO:$TAG on port $HTTP_PORT"
docker compose up -d --remove-orphans \
  || rollback_or_die "docker compose up failed for $IMAGE_REPO:$TAG — check for a port conflict on $HTTP_PORT or a malformed app.env."

if healthy; then
  echo "deploy: healthy — http://127.0.0.1:$HTTP_PORT/ is serving $IMAGE_REPO:$TAG"
  prune_images "$TAG" "$PREVIOUS_TAG"
  exit 0
fi

rollback_or_die "$IMAGE_REPO:$TAG failed the health check after ${HEALTH_TIMEOUT}s"
