#!/usr/bin/env bash
# Host-side deploy for the self-hosted gnomon dashboard.
#
#   ./deploy.sh <image-tag>
#
# Copied to ~/gnomon by .github/workflows/dashboard-deploy.yml, but designed to
# be run by hand — that is the rollback path. With tmp/image.tar.gz present the
# tag is loaded from it; without, the tag must already be in the local store.
#
# Env: HTTP_PORT (80), HEALTH_TIMEOUT (60), HEALTH_INTERVAL (2)
set -euo pipefail

cd "$(dirname "$0")"

IMAGE_REPO=gnomon-dashboard
TARBALL=tmp/image.tar.gz
HTTP_PORT="${HTTP_PORT:-80}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-60}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-2}"

die() {
  echo "deploy: $*" >&2
  exit 1
}

preflight() {
  docker version >/dev/null 2>&1 || die \
    "cannot reach the Docker daemon as $(id -un). Install Docker Engine and add this user to the docker group: sudo usermod -aG docker $(id -un) — then log out and back in."
  docker compose version >/dev/null 2>&1 || die \
    "the Docker Compose plugin is missing. Install docker-compose-plugin (v2); the standalone docker-compose script is not used here."
  mkdir -p data tmp
  # Checked before anything starts: a data/ the container cannot write to
  # otherwise surfaces as a confusing SQLite SQLITE_CANTOPEN *after* an
  # apparently green deploy.
  [ -w data ] || die \
    "$(pwd)/data is not writable by $(id -un). The container writes the SQLite DB there. Fix with: sudo chown -R $(id -u):$(id -g) $(pwd)/data"
}

# The tag currently deployed, or empty on a first deploy.
current_tag() {
  [ -f .env ] || return 0
  sed -n 's/^IMAGE_TAG=//p' .env | tail -n1
}

# $1 = IMAGE_TAG, $2 = PREVIOUS_TAG
write_env() {
  cat > .env <<EOF
# GENERATED BY deploy.sh — do not hand-edit; the next deploy overwrites it.
# Compose interpolation only. Application secrets live in app.env.
IMAGE_TAG=$1
PREVIOUS_TAG=$2
DEPLOY_UID=$(id -u)
DEPLOY_GID=$(id -g)
HTTP_PORT=$HTTP_PORT
EOF
}

load_image() {
  if [ -f "$TARBALL" ]; then
    gunzip -c "$TARBALL" | docker load
    rm -f "$TARBALL"
  fi
  docker image inspect "$IMAGE_REPO:$TAG" >/dev/null 2>&1 || die \
    "image $IMAGE_REPO:$TAG is not in the local store and no $TARBALL was supplied. To roll back, pass a tag that is still loaded: docker image ls $IMAGE_REPO"
}

# Polls the published port from the host — the same endpoint
# .github/workflows/dashboard-image.yml already uses as a readiness probe.
healthy() {
  local deadline=$((SECONDS + HEALTH_TIMEOUT))
  while [ "$SECONDS" -lt "$deadline" ]; do
    if curl -fsS -o /dev/null "http://127.0.0.1:$HTTP_PORT/"; then
      return 0
    fi
    sleep "$HEALTH_INTERVAL"
  done
  return 1
}

TAG="${1:-}"
[ -n "$TAG" ] || {
  echo "usage: deploy.sh <image-tag>" >&2
  exit 2
}

preflight

# Unconditional: a failure anywhere below must not leave hundreds of megabytes
# sitting in the operator's home directory.
trap 'rm -f "$TARBALL"' EXIT

load_image

PREVIOUS_TAG="$(current_tag)"
write_env "$TAG" "$PREVIOUS_TAG"

echo "deploy: starting $IMAGE_REPO:$TAG on port $HTTP_PORT"
docker compose up -d --remove-orphans

if healthy; then
  echo "deploy: healthy — http://127.0.0.1:$HTTP_PORT/ is serving $IMAGE_REPO:$TAG"
  exit 0
fi

echo "deploy: $IMAGE_REPO:$TAG failed the health check after ${HEALTH_TIMEOUT}s" >&2
docker compose logs --tail=100 >&2 || true
die "deploy failed"
